import type { Metadata } from "next";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ZenithApp",
  description: "Generated by zenithApp",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="relative min-h-screen overflow-hidden">

      <div className="fixed inset-0 -z-50 bg-[#122a57]">
        
        <div className="absolute top-0 right-0 h-[300px] w-[300px] -translate-x-[240%] translate-y-[70%] rounded-full opacity-50 blur-[80px] z-[-40]"></div>
      </div>

      <div className="relative z-0 px-0 sm:px-0 md:px-0 lg:px-20 xl:px-40 lg:pt-16 pb-10">
        {children}
      </div>
    </main>
  );
}
